//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBand.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingPaymentsConfiguration
    {
        public int ID { get; set; }
        public Nullable<int> ServiceType { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<int> OperatorID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> BillingPaymentID { get; set; }
        public string ServiceName { get; set; }
        public string Info1 { get; set; }
        public string Info2 { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual BillingPayment BillingPayment { get; set; }
        public virtual Country Country { get; set; }
        public virtual Operator Operator { get; set; }
    }
}
