//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBand.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerOTP
    {
        public long ID { get; set; }
        public Nullable<long> CusomerID { get; set; }
        public Nullable<long> DeviceID { get; set; }
        public Nullable<int> WalletServiceID { get; set; }
        public string OTP { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UsedDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> isUsed { get; set; }
    
        public virtual CustomerDevice CustomerDevice { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual WalletService WalletService { get; set; }
    }
}
