//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBand.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerMobileNoHistory
    {
        public long ID { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public string WallerServiceCode { get; set; }
        public string MobileNumber { get; set; }
        public string EmailID { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Description { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
