//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBand.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerOTP_SMSs
    {
        public long ID { get; set; }
        public string MobileNo { get; set; }
        public string Message { get; set; }
        public string Lang { get; set; }
        public string SenderID { get; set; }
        public string Username { get; set; }
        public string ResponseMessage { get; set; }
        public string Reference { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
