//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBand.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerWallet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerWallet()
        {
            this.CustomerWalletTransactions = new HashSet<CustomerWalletTransaction>();
        }
    
        public long ID { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public string WalletCode { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string WalletPassCode { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerWalletTransaction> CustomerWalletTransactions { get; set; }
    }
}
