//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBand.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.CustomerDevices = new HashSet<CustomerDevice>();
            this.CustomerMobileNoHistories = new HashSet<CustomerMobileNoHistory>();
            this.CustomerOTPs = new HashSet<CustomerOTP>();
            this.LoyaltyCustomerCards = new HashSet<LoyaltyCustomerCard>();
            this.CustomerWallets = new HashSet<CustomerWallet>();
        }
    
        public long ID { get; set; }
        public string CountryCode { get; set; }
        public string CustomerCode { get; set; }
        public string Password { get; set; }
        public string MobileNo { get; set; }
        public Nullable<bool> MobileActivated { get; set; }
        public Nullable<short> OTP { get; set; }
        public string Email { get; set; }
        public Nullable<bool> EmailActivated { get; set; }
        public string CivilID { get; set; }
        public Nullable<bool> CivilIDActivated { get; set; }
        public string AppIdentifier { get; set; }
        public Nullable<System.DateTime> TranDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public byte[] EncryptedPassword { get; set; }
        public string profileSource { get; set; }
        public byte[] paymentTokenAlias { get; set; }
        public string CardType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerDevice> CustomerDevices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerMobileNoHistory> CustomerMobileNoHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerOTP> CustomerOTPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoyaltyCustomerCard> LoyaltyCustomerCards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerWallet> CustomerWallets { get; set; }
    }
}
