//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBand.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerWalletTransactionsDebit
    {
        public long ID { get; set; }
        public Nullable<long> WalletTransactionID { get; set; }
        public string DebitServiceName { get; set; }
        public string DebitReference { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Description { get; set; }
    
        public virtual CustomerWalletTransaction CustomerWalletTransaction { get; set; }
    }
}
