//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBand.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InteractiveServiceContestant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InteractiveServiceContestant()
        {
            this.ContestantsReports_Day = new HashSet<ContestantsReports_Day>();
            this.ContestantsReports_Hour = new HashSet<ContestantsReports_Hour>();
            this.ContestantsReports_Month = new HashSet<ContestantsReports_Month>();
            this.ContestantsReports_Year = new HashSet<ContestantsReports_Year>();
            this.InteractiveServiceContestants1 = new HashSet<InteractiveServiceContestant>();
            this.InteractiveServiceContestantsVotes = new HashSet<InteractiveServiceContestantsVote>();
        }
    
        public int ID { get; set; }
        public Nullable<int> InteractiveServiceID { get; set; }
        public Nullable<int> ContestantID { get; set; }
        public Nullable<int> OperatorID { get; set; }
        public string UserMsg { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Info1 { get; set; }
        public string Info2 { get; set; }
        public string ImageURL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContestantsReports_Day> ContestantsReports_Day { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContestantsReports_Hour> ContestantsReports_Hour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContestantsReports_Month> ContestantsReports_Month { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContestantsReports_Year> ContestantsReports_Year { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InteractiveServiceContestant> InteractiveServiceContestants1 { get; set; }
        public virtual InteractiveServiceContestant InteractiveServiceContestant1 { get; set; }
        public virtual InteractiveService InteractiveService { get; set; }
        public virtual Operator Operator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InteractiveServiceContestantsVote> InteractiveServiceContestantsVotes { get; set; }
    }
}
