//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBand.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class KYCParameter
    {
        public KYCParameter()
        {
            this.KYCParametersCountries = new HashSet<KYCParametersCountry>();
            this.WalletTypeCountries = new HashSet<WalletTypeCountry>();
        }
    
        public int ID { get; set; }
        public string KYCAlias { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public bool isFirstNameRequired { get; set; }
        public bool isLastNameRequired { get; set; }
        public bool isFullNameRequired { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public bool isDOBRequired { get; set; }
        public string Gender { get; set; }
        public bool isGenderRequired { get; set; }
        public string Nationality { get; set; }
        public bool isNationalityRequired { get; set; }
        public string PlaceOfBirth { get; set; }
        public bool isPlaceOfBirthRequired { get; set; }
        public string IDProofNo1Label { get; set; }
        public bool isIDProof1Required { get; set; }
        public bool isProof1DoublePaged { get; set; }
        public string IDProofNo2Label { get; set; }
        public bool isIDProof2Required { get; set; }
        public bool isProof2DoublePaged { get; set; }
        public string IDProofNo3Label { get; set; }
        public bool isIDProof3Required { get; set; }
        public bool isProof3DoublePaged { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Info1 { get; set; }
        public string Info2 { get; set; }
        public string Info3 { get; set; }
    
        public virtual ICollection<KYCParametersCountry> KYCParametersCountries { get; set; }
        public virtual ICollection<WalletTypeCountry> WalletTypeCountries { get; set; }
    }
}
