//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBand.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoyaltyCardType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoyaltyCardType()
        {
            this.LoyaltyCustomerCards = new HashSet<LoyaltyCustomerCard>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public Nullable<int> LoyaltyCardCompanyID { get; set; }
        public string CardType { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual LoyaltyCardCompany LoyaltyCardCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoyaltyCustomerCard> LoyaltyCustomerCards { get; set; }
    }
}
