//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBand.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MerchantRequest
    {
        public int ID { get; set; }
        public string CompanyName { get; set; }
        public string Name { get; set; }
        public string Subject { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Message { get; set; }
        public string FilePath { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
