//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBand.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MerchantTransaction
    {
        public int ID { get; set; }
        public Nullable<int> MerchantID { get; set; }
        public string Reference { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Merchant Merchant { get; set; }
    }
}
