//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBand.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MerchantOrderItem
    {
        public int ID { get; set; }
        public Nullable<long> MerchantOrderID { get; set; }
        public Nullable<int> MerchantItemID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public string StatusDescription { get; set; }
        public Nullable<double> ItemAmount { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual MerchantItem MerchantItem { get; set; }
        public virtual MerchantOrder MerchantOrder { get; set; }
    }
}
