//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBand.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MerchantItemImage
    {
        public int MerchantImageID { get; set; }
        public string ImageURL { get; set; }
        public Nullable<int> MerchantItemID { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
    
        public virtual MerchantItem MerchantItem { get; set; }
    }
}
