//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBand.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayitiSY
    {
        public long ID { get; set; }
        public Nullable<long> IsysID { get; set; }
        public Nullable<long> TransactionID { get; set; }
        public Nullable<long> OperatorOrderID { get; set; }
        public string MobileNo { get; set; }
        public string Service { get; set; }
        public Nullable<double> Amount { get; set; }
        public System.DateTime TranDate { get; set; }
        public Nullable<System.DateTime> ProcessTranDate { get; set; }
        public string ProcessTranDescription { get; set; }
        public string PaymentAPI { get; set; }
    }
}
