//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBand.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfilesKYCHistory
    {
        public long ID { get; set; }
        public Nullable<long> ProfileKYCID { get; set; }
        public Nullable<long> ProfileID { get; set; }
        public string Action { get; set; }
        public string ActionDescription { get; set; }
        public string ActionStatus { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> KYCRating { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual ProfilesKYC ProfilesKYC { get; set; }
        public virtual ProfilesKYC ProfilesKYC1 { get; set; }
    }
}
