//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBand.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public Profile()
        {
            this.ProfilesKYCs = new HashSet<ProfilesKYC>();
            this.Wallets = new HashSet<Wallet>();
            this.WalletTransactions = new HashSet<WalletTransaction>();
        }
    
        public long ID { get; set; }
        public Nullable<long> UserIdentifier { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<bool> isMobileVerified { get; set; }
        public Nullable<bool> isEmailVerified { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Info1 { get; set; }
        public string Info2 { get; set; }
        public string CountryCode { get; set; }
        public Nullable<int> KYCRating { get; set; }
    
        public virtual ICollection<ProfilesKYC> ProfilesKYCs { get; set; }
        public virtual ICollection<Wallet> Wallets { get; set; }
        public virtual ICollection<WalletTransaction> WalletTransactions { get; set; }
    }
}
