//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBand.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RBTMeta
    {
        public int ID { get; set; }
        public string ToneName { get; set; }
        public Nullable<long> ToneID { get; set; }
        public string ToneDescription { get; set; }
        public string CategoryName { get; set; }
        public string CompanyName { get; set; }
        public string CompanyType { get; set; }
        public string AlbumName { get; set; }
        public string AlbumLanguage { get; set; }
        public string AlbumDescription { get; set; }
        public string ArtistName { get; set; }
        public string Gender { get; set; }
        public string Occupation { get; set; }
        public string Operator { get; set; }
        public string RBTName { get; set; }
        public string RBTDescription { get; set; }
        public string ProductID { get; set; }
        public string UserMsg { get; set; }
        public string ShortCode { get; set; }
        public Nullable<int> ValidityPeriod { get; set; }
        public string Price { get; set; }
        public string Country { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> MetaMaster { get; set; }
    
        public virtual MetaMaster MetaMaster1 { get; set; }
    }
}
