//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBand.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanctionsList
    {
        public int ID { get; set; }
        public string FullName { get; set; }
        public Nullable<int> DOBDate { get; set; }
        public Nullable<int> DOBMonth { get; set; }
        public Nullable<int> DOBYear { get; set; }
        public string Nationality { get; set; }
        public string CountryCode { get; set; }
        public string PassportNo { get; set; }
        public string NationalIdentityNumber { get; set; }
        public string Address { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Info1 { get; set; }
        public string Info2 { get; set; }
        public string Info3 { get; set; }
        public string Info4 { get; set; }
        public string Source { get; set; }
        public string SourceDocInformation { get; set; }
        public string SourceID { get; set; }
    }
}
