//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBand.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subs_ContentGroupConfig
    {
        public int ID { get; set; }
        public Nullable<int> ContentOwnerID { get; set; }
        public string GroupName { get; set; }
        public int ContentType { get; set; }
        public Nullable<int> ContentDataID { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Info1 { get; set; }
        public string Info2 { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> SubCategoryID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        public virtual Subs_ContentData Subs_ContentData { get; set; }
        public virtual Subs_ContentGroups Subs_ContentGroups { get; set; }
        public virtual Subs_ContentOwners Subs_ContentOwners { get; set; }
    }
}
