//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBand.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subs_ContentData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subs_ContentData()
        {
            this.Subs_ContentGroupConfig = new HashSet<Subs_ContentGroupConfig>();
        }
    
        public int ID { get; set; }
        public string ContentName { get; set; }
        public string ContentDescription { get; set; }
        public Nullable<int> ContentType { get; set; }
        public string ContentData { get; set; }
        public bool Status { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> SubCategoryID { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        public virtual Subs_ContentOwners Subs_ContentOwners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subs_ContentGroupConfig> Subs_ContentGroupConfig { get; set; }
    }
}
