//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBand.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThirdPartyApp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThirdPartyApp()
        {
            this.ThirdPartyAppPrivileges = new HashSet<ThirdPartyAppPrivilege>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ThirdPartyID { get; set; }
        public string AppName { get; set; }
        public string AppCode { get; set; }
        public string AppType { get; set; }
        public string AppURL { get; set; }
        public Nullable<double> Version { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual ThirdParty ThirdParty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThirdPartyAppPrivilege> ThirdPartyAppPrivileges { get; set; }
    }
}
