//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBand.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThirdParty_knet_trans
    {
        public int myid { get; set; }
        public string company { get; set; }
        public string Tuser { get; set; }
        public string Tpass { get; set; }
        public string Tresponse_link { get; set; }
        public long TId { get; set; }
        public string IsysId { get; set; }
        public string amt { get; set; }
        public string ptype { get; set; }
        public Nullable<long> trackid { get; set; }
        public Nullable<decimal> payid { get; set; }
        public Nullable<decimal> transid { get; set; }
        public Nullable<decimal> refid { get; set; }
        public Nullable<int> postdate { get; set; }
        public string knetprocess { get; set; }
        public string rawresponse { get; set; }
        public string errmsg { get; set; }
        public string udf1 { get; set; }
        public string udf2 { get; set; }
        public string udf3 { get; set; }
        public string udf4 { get; set; }
        public string udf5 { get; set; }
        public Nullable<System.DateTime> tdatetime { get; set; }
        public Nullable<System.DateTime> LastUpdateOn { get; set; }
    }
}
