//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBand.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThirdPartyAppPrivilege
    {
        public int ID { get; set; }
        public Nullable<int> ThirdPartyAppID { get; set; }
        public Nullable<int> UsersNWalletPrivilegeID { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual ThirdPartyApp ThirdPartyApp { get; set; }
        public virtual UsersNWalletPrivilege UsersNWalletPrivilege { get; set; }
    }
}
