//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBand.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WalletTransaction
    {
        public long ID { get; set; }
        public Nullable<long> WalletAccountID { get; set; }
        public Nullable<long> ProfileID { get; set; }
        public Nullable<int> WalletTypeID { get; set; }
        public Nullable<long> UserIdentifier { get; set; }
        public string TransactionType { get; set; }
        public string TransactionRef { get; set; }
        public string UserMobile { get; set; }
        public string UserEmail { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string PaymentService { get; set; }
        public string PaymentReference { get; set; }
        public string PaymentAccountType { get; set; }
        public string PaymentStatusDescription { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> TransactionAmount { get; set; }
        public string Currency { get; set; }
        public string TransactionCurrency { get; set; }
        public string TransactionStatus { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Info1 { get; set; }
        public string Info2 { get; set; }
    
        public virtual Profile Profile { get; set; }
        public virtual WalletAccount WalletAccount { get; set; }
        public virtual WalletType WalletType { get; set; }
    }
}
