//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBand.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WalletsEntities : DbContext
    {
        public WalletsEntities()
            : base("name=WalletsEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KYCParameter> KYCParameters { get; set; }
        public virtual DbSet<KYCParametersCountry> KYCParametersCountries { get; set; }
        public virtual DbSet<KYCRatingRule> KYCRatingRules { get; set; }
        public virtual DbSet<KYCRatingValidation> KYCRatingValidations { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<ProfilesKYC> ProfilesKYCs { get; set; }
        public virtual DbSet<ProfilesKYCHistory> ProfilesKYCHistories { get; set; }
        public virtual DbSet<SanctionsList> SanctionsLists { get; set; }
        public virtual DbSet<Wallet> Wallets { get; set; }
        public virtual DbSet<WalletAccount> WalletAccounts { get; set; }
        public virtual DbSet<WalletTransaction> WalletTransactions { get; set; }
        public virtual DbSet<WalletTypeCountry> WalletTypeCountries { get; set; }
        public virtual DbSet<WalletType> WalletTypes { get; set; }
    
        public virtual ObjectResult<GetProfileswithKYC_Result> GetProfileswithKYC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProfileswithKYC_Result>("GetProfileswithKYC");
        }
    }
}
