//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBand.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WalletAccount
    {
        public WalletAccount()
        {
            this.WalletTransactions = new HashSet<WalletTransaction>();
        }
    
        public long ID { get; set; }
        public Nullable<long> WalletID { get; set; }
        public Nullable<int> WalletTypeID { get; set; }
        public Nullable<long> UserIdentifier { get; set; }
        public Nullable<bool> UseCustomerLogin { get; set; }
        public Nullable<bool> SMSAuthenticatedTransaction { get; set; }
        public string CVVAuthentcatedTransaction { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<double> Balance { get; set; }
        public string Currency { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Info1 { get; set; }
        public string Info2 { get; set; }
        public string Info3 { get; set; }
        public string Info4 { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<int> WalletTypeCountryID { get; set; }
    
        public virtual Wallet Wallet { get; set; }
        public virtual WalletTypeCountry WalletTypeCountry { get; set; }
        public virtual WalletType WalletType { get; set; }
        public virtual ICollection<WalletTransaction> WalletTransactions { get; set; }
    }
}
