//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBand.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WalletType
    {
        public WalletType()
        {
            this.WalletAccounts = new HashSet<WalletAccount>();
            this.WalletTransactions = new HashSet<WalletTransaction>();
            this.WalletTypeCountries = new HashSet<WalletTypeCountry>();
        }
    
        public int ID { get; set; }
        public string WalletTypeName { get; set; }
        public bool UseCustomerLogin { get; set; }
        public bool SMSAuthenticatedTransaction { get; set; }
        public string CVVAuthentcatedTransaction { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Info1 { get; set; }
        public string Info2 { get; set; }
    
        public virtual ICollection<WalletAccount> WalletAccounts { get; set; }
        public virtual ICollection<WalletTransaction> WalletTransactions { get; set; }
        public virtual ICollection<WalletTypeCountry> WalletTypeCountries { get; set; }
    }
}
