//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBand.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WalletTypeCountry
    {
        public WalletTypeCountry()
        {
            this.WalletAccounts = new HashSet<WalletAccount>();
        }
    
        public int ID { get; set; }
        public Nullable<int> WalletTypeID { get; set; }
        public string WalletName { get; set; }
        public string WalletCode { get; set; }
        public string Country { get; set; }
        public bool isDefault { get; set; }
        public Nullable<int> KYCParameterID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public bool Status { get; set; }
    
        public virtual KYCParameter KYCParameter { get; set; }
        public virtual ICollection<WalletAccount> WalletAccounts { get; set; }
        public virtual WalletType WalletType { get; set; }
    }
}
